server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db.vuwbestrxltqzyojbjjn.supabase.co:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mypassword#@!12345678910
    hikari:
      maximum-pool-size: 90
      minimum-idle: 50
      connection-timeout: 30000
      idle-timeout: 600000
      pool-name: HikariConnPool
      max-lifetime: 1800000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        integration.blazebit.enabled: true

api:
  prefix: api/v1

jwt:
  signerKey: fa0104b714daed2e4d470c47efc8974969a1a5b6310e3e216f8bfc77cf5bd46cd5d830dbed507f85213a03dcec3e2d616497f59f5aacdf67c0cd8b6320f2e2f9
  valid-duration: 3600 # seconds
  refreshable-duration: 3600000

blazebit:
  entity-view:
    enabled: true
