server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 90
      minimum-idle: 50
      connection-timeout: 30000
      idle-timeout: 600000
      pool-name: HikariConnPool
      max-lifetime: 1800000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        integration.blazebit.enabled: true

api:
  prefix: api/v1

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600 # seconds
  refreshable-duration: 3600000

blazebit:
  entity-view:
    enabled: true
