server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/dadn
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 90
      minimum-idle: 50
      connection-timeout: 30000
      idle-timeout: 600000
      pool-name: HikariConnPool
      max-lifetime: 1800000

  google:
    oauth:
      client-id: ${GOOGLE_OAUTH_CLIENT_ID}
      client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}



  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        integration.blazebit.enabled: true

api:
  prefix: api/v1

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600 # seconds
  refreshable-duration: 3600000

blazebit:
  entity-view:
    enabled: true